version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-ssr-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment để mount logs volume
    # volumes:
    #   - ./logs:/app/logs
    
    # Uncomment để thêm networks tùy chỉnh
    # networks:
    #   - app-network

# Uncomment để tạo custom network
# networks:
#   app-network:
#     driver: bridge

# Uncomment để thêm volumes cho persistent data
# volumes:
#   app-logs:
#     driver: local